  - hosts: all
    become: yes
    tasks:
    - name: Install packages
      apt:
        name:
          - openvpn
          - easy-rsa
          - selinux-utils
        state: present
        update_cache: true

    - name: disable SElinux now
      shell: setenforce 0
      ignore_errors: true

  - hosts: server
    become: yes
    tasks:

    - name: init PKI and generate keys and certs
      shell: "{{ item }}"
      args:
        chdir: /etc/openvpn
      with_items:
        - /usr/share/easy-rsa/easyrsa init-pki 
        - echo 'rasvpn' | /usr/share/easy-rsa/easyrsa build-ca nopass 
        - echo 'rasvpn' | /usr/share/easy-rsa/easyrsa gen-req server nopass 
        - echo 'yes' | /usr/share/easy-rsa/easyrsa sign-req server server
        - /usr/share/easy-rsa/easyrsa gen-dh 
        - openvpn --genkey secret ca.key 
        - echo 'client' | /usr/share/easy-rsa/easyrsa gen-req client nopass 
        - echo 'yes' | /usr/share/easy-rsa/easyrsa sign-req client client 
        - echo 'iroute 10.10.10.0 255.255.255.0' > /etc/openvpn/client/client


    - name: create /etc/openvpn/server.conf
      template:
        src: server_ras.conf
        dest: /etc/openvpn/server.conf

    - name: enable openvpn
      service:
        name: "openvpn@server"
        state: started
        enabled: true

    - name: Fetch static key
      fetch:
        src: '{{item}}' 
        dest: tmp
      loop:
        - /etc/openvpn/pki/ca.crt
        - /etc/openvpn/pki/issued/client.crt 
        - /etc/openvpn/pki/private/client.key

  - hosts: client
    tasks:
    
    - name: Create /home/vagrant/openvpn directory for openvpn files
      file:
        path: /home/vagrant/openvpn
        state: directory
        mode: '0755'

    - name: Put client.conf to /home/vagrant/openvpn
      template:
        src: server_rasclient.conf
        dest: /home/vagrant/openvpn/client.conf

    - name: Copy static key to client VM
      copy:
        src: '{{item}}'
        dest: /home/vagrant/openvpn/
      loop:
        - tmp/server/etc/openvpn/pki/ca.crt
        - tmp/server/etc/openvpn/pki/issued/client.crt
        - tmp/server/etc/openvpn/pki/private/client.key

